FROM apache/airflow:2.9.3-python3.11

USER airflow

RUN pip install --no-cache-dir \
    "dbt-core==1.9.4" \
    "dbt-snowflake==1.9.0" \
    snowflake-connector-python \
    pandas \
    pyarrow \
    psycopg2-binary \
    python-dotenv